package io.darkstrata.credentialcheck;

/**
 * Source of the HMAC key used for the check.
 */
public enum HmacSource {
    /**
     * HMAC key was generated by the server.
     */
    SERVER,

    /**
     * HMAC key was provided by the client.
     */
    CLIENT
}
